services:
  # Base de dados
  postgres:
    image: postgres:16-alpine
    container_name: ff-postgres
    environment:
      POSTGRES_DB: feature_flags
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ff-network
    restart: unless-stopped

  # Cache
  redis:
    image: redis:7-alpine
    container_name: ff-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ff-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ff-network:
    driver: bridge
    name: feature-flags-network
