global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "feature-flags"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
    scrape_interval: 10s

  # PostgreSQL e Redis precisam de exporters específicos
  # Para coletar métricas deles, você precisaria adicionar:
  # - postgres_exporter para PostgreSQL
  # - redis_exporter para Redis

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
